version: "3.8"
 
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: policy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - fullstack-net
 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/policy?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:9091"
    networks:
      - fullstack-net

 
volumes:
  mysql_data:
 
networks:
  fullstack-net:
